DROP TABLE IF EXISTS tracks CASCADE;

CREATE TABLE tracks (
  id SERIAL PRIMARY KEY NOT NULL,
  playlist_id INTEGER REFERENCES playlists(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL,
  source BYTEA NOT NULL,
  mime_type VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);